<?php

return [
    'default_brand' => 'rnb',

    'phone' => '085198210060',

    'aliases' => [
        'andalan' => 'andalanku',
    ],

    'domains' => [
        'localhost' => 'rnb',
        '127.0.0.1' => 'rnb',
        'www.rnbmanagement.com' => 'rnb',
        'rnbmanagement.com' => 'rnb',
        'andalanku.com' => 'andalanku',
        'www.andalanku.com' => 'andalanku',
        'andalanbersamamigration.com' => 'andalanku',
        'www.andalanbersamamigration.com' => 'andalanku',
        'kma.co.id' => 'kma',
        'www.kma.co.id' => 'kma',
        'niskala.co.id' => 'niskala',
        'www.niskala.co.id' => 'niskala',
        'rne.co.id' => 'rne',
        'www.rne.co.id' => 'rne',
        'tms.co.id' => 'tms',
        'www.tms.co.id' => 'tms',
        'trah.co.id' => 'trah',
        'www.trah.co.id' => 'trah',
    ],

    'brands' => [
        'rnb' => [
            'name' => 'RNB Management',
            'logo' => 'images/Logo RNB.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20RNB.png',
            'website' => 'https://www.rnbmanagement.com/',
            'email' => 'hr@rnb.co.id',
            'primary_color' => '#b01020',
            'accent_color' => '#8c6d00',
            'header_background_color' => '#fff8e6',
            'header_text_color' => '#172033',
        ],
        'andalanku' => [
            'name' => 'AndalanKu',
            'logo' => 'images/Logo AndalanKu.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20AndalanKu.png',
            'website' => 'https://andalanku.com/',
            'email' => 'recruitment@andalanku.com',
            'primary_color' => '#900000',
            'accent_color' => '#d02020',
            'header_background_color' => '#fff5f5',
            'header_text_color' => '#172033',
        ],
        'kma' => [
            'name' => 'KMA',
            'logo' => 'images/Logo KMA.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20KMA.png',
            'website' => 'https://kma.co.id/',
            'email' => 'hr@karpetmerah.id',
            'primary_color' => '#b01020',
            'accent_color' => '#e01020',
            'header_background_color' => '#fff5f5',
            'header_text_color' => '#172033',
        ],
        'niskala' => [
            'name' => 'Niskala',
            'logo' => 'images/Logo Niskala.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20Niskala.png',
            'website' => 'https://niskala.co.id/',
            'email' => 'hr@coffeeniskala.com',
            'primary_color' => '#6f6f58',
            'accent_color' => '#76765f',
            'header_background_color' => '#f7f6ef',
            'header_text_color' => '#172033',
        ],
        'rne' => [
            'name' => 'RNE',
            'logo' => 'images/Logo RNE.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20RNE.png',
            'website' => 'https://rne.co.id/',
            'email' => 'hr@rne.co.id',
            'primary_color' => '#b01020',
            'accent_color' => '#8c6d00',
            'header_background_color' => '#fff8e6',
            'header_text_color' => '#172033',
        ],
        'tms' => [
            'name' => 'TMS',
            'logo' => 'images/Logo TMS.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20TMS.png',
            'website' => 'https://tms.co.id/',
            'email' => 'hr@tims.co.id',
            'primary_color' => '#202090',
            'accent_color' => '#b35f00',
            'header_background_color' => '#f4f6ff',
            'header_text_color' => '#172033',
        ],
        'trah' => [
            'name' => 'Trah',
            'logo' => 'images/Logo Trah.png',
            'logo_url' => 'https://raw.githubusercontent.com/dimas-prayoga26/web_careers_company/main/public/images/Logo%20Trah.png',
            'website' => 'https://trah.co.id/',
            'email' => 'hr@trah.co.id',
            'primary_color' => '#7a6035',
            'accent_color' => '#8a6d3e',
            'header_background_color' => '#f7f2e6',
            'header_text_color' => '#172033',
        ],
    ],
];
